#!/usr/bin/env bash
# Installs the toolchain for tools/check.sh into $FACTORIO_LUA_HOME (default ~/.local/share/factorio-lua):
#   <root>/5.2                          PUC-Rio Lua 5.2.4 + LuaRocks (hererocks), the language version Factorio runs
#   <root>/5.2/bin/luacheck
#   <root>/emmylua/<ver>/emmylua_check  prebuilt release binary, sha256-checked (Linux x64, macOS arm64)
#   <root>/fmtk/<api>/factorio/library  EmmyLua library of the Factorio API, generated by fmtk from lua-api.factorio.com
# Versions are pinned in tools/versions.sh; steps already done are skipped. fmtk comes from package.json, so run
# `pnpm install` first.
#   tools/setup.sh
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(dirname "$here")"
# shellcheck source=tools/versions.sh
source "$here/versions.sh"
root="${FACTORIO_LUA_HOME:-$HOME/.local/share/factorio-lua}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

lua_home="$root/5.2"
if [ ! -x "$lua_home/bin/lua" ]; then
  curl -sfL "https://raw.githubusercontent.com/luarocks/hererocks/$hererocks_commit/hererocks.py" -o "$tmp/hererocks.py"
  python3 "$tmp/hererocks.py" "$lua_home" -l 5.2 -r latest --no-readline
fi
"$lua_home/bin/lua" -v

if [ ! -x "$lua_home/bin/luacheck" ]; then
  "$lua_home/bin/luarocks" install luacheck "$luacheck_version"
fi
"$lua_home/bin/luacheck" --version | head -1

emmylua_home="$root/emmylua/$emmylua_version"
if [ ! -x "$emmylua_home/emmylua_check" ]; then
  case "$(uname -sm)" in
    "Linux x86_64") platform=linux-x64; sha256=$emmylua_sha256_linux_x64 ;;
    "Darwin arm64") platform=darwin-arm64; sha256=$emmylua_sha256_darwin_arm64 ;;
    *) echo "error: no pinned emmylua_check for $(uname -sm); install $emmylua_version into $emmylua_home by hand" >&2; exit 1 ;;
  esac
  curl -sfL "https://github.com/EmmyLuaLs/emmylua-analyzer-rust/releases/download/$emmylua_version/emmylua_check-$platform.tar.gz" \
    -o "$tmp/emmylua_check.tar.gz"
  echo "$sha256  $tmp/emmylua_check.tar.gz" | shasum -a 256 -c - > /dev/null
  mkdir -p "$emmylua_home"
  tar -xzf "$tmp/emmylua_check.tar.gz" -C "$emmylua_home"
fi
"$emmylua_home/emmylua_check" --version

api_out="$root/fmtk/$factorio_api_version"
if [ ! -d "$api_out/factorio/library" ]; then
  for api in runtime prototype; do
    curl -sfL "https://lua-api.factorio.com/$factorio_api_version/$api-api.json" -o "$tmp/$api-api.json"
  done
  mkdir -p "$api_out"
  (cd "$repo" && pnpm exec fmtk docs -d "$tmp/runtime-api.json" -p "$tmp/prototype-api.json" "$api_out")
fi
echo "Factorio API library $factorio_api_version: $api_out/factorio/library"
